import type { TInstalledEquipment } from '@/shared/model';

export const MOCK_INSTALLED_EQUIPMENT: TInstalledEquipment[] = [
    {
        id: '1',
        msProductId: 'ms-product-1',
        productName: 'Система фильтрации Аквафор Трио',
        installedAt: '2026-01-15T10:00:00.000Z',
        isActive: true,
        notificationsEnabled: true,
        realEstate: { id: 1 },
        components: [
            {
                id: 'c1',
                msProductId: 'ms-filter-k5',
                componentName: 'Картридж K5 (механическая очистка)',
                baseLifespanMonths: 6,
                adjustedLifespanMonths: 4,
                installedAt: '2026-01-15T10:00:00.000Z',
                nextReplacementDate: '2026-05-10T10:00:00.000Z',
                isReplaced: false,
            },
            {
                id: 'c2',
                msProductId: 'ms-filter-k7',
                componentName: 'Картридж K7 (удаление хлора)',
                baseLifespanMonths: 12,
                adjustedLifespanMonths: 8,
                installedAt: '2026-01-15T10:00:00.000Z',
                nextReplacementDate: '2026-07-01T10:00:00.000Z',
                isReplaced: false,
            },
            {
                id: 'c3',
                msProductId: 'ms-filter-k7b',
                componentName: 'Постфильтр K7B',
                baseLifespanMonths: 24,
                adjustedLifespanMonths: 18,
                installedAt: '2026-01-15T10:00:00.000Z',
                nextReplacementDate: '2026-12-15T10:00:00.000Z',
                isReplaced: false,
            },
        ],
    },
    {
        id: '2',
        msProductId: 'ms-product-2',
        productName: 'Умягчитель воды EcoWater ERR 3500',
        installedAt: '2026-02-20T10:00:00.000Z',
        isActive: true,
        notificationsEnabled: false,
        realEstate: { id: 1 },
        components: [
            {
                id: 'c4',
                msProductId: 'ms-salt-tablet',
                componentName: 'Соль таблетированная (25 кг)',
                baseLifespanMonths: 2,
                adjustedLifespanMonths: 1,
                installedAt: '2026-03-01T10:00:00.000Z',
                nextReplacementDate: '2026-04-15T10:00:00.000Z',
                isReplaced: false,
            },
        ],
    },
    {
        id: '3',
        msProductId: 'ms-product-3',
        productName: 'Фильтр Аквафор Модерн (б/у)',
        installedAt: '2024-06-01T10:00:00.000Z',
        isActive: false,
        notificationsEnabled: false,
        realEstate: { id: 1 },
        components: [],
    },
];
